### ISSUE TITLE
How to access?

### ISSUE THREAD

**Issue by appcornerit** [koel/app#20]
Hi, I'm running macOS 10.14.3, the first page ask for host/email/password, after pressing on the login button it stay on the same page.
What I'm doing wrong?
Btw I tried to compile the koel project and it didn't work, I tried to run the docker image and it didn't work, now I tried the app and is stacked to the login page.
Thanks.

**Comment by svalo** [comment]
I think you should insert the host with proper http(s):// part, something like https://mykoel.com 

Just got stuck on same problem and solved this way
